"""Real Bahria University (E-8) Computer Science faculty roster.

Captured from https://www.bahria.edu.pk/ (Department of Computer Science, E-8).
Names and designations are the real published roster. ``areas`` holds real
Research Areas / Expertise where captured from the faculty detail pages;
blank areas are assigned realistic topics by the seed generator.
"""
from __future__ import annotations

# (name, designation, real research areas or "")
ROSTER: list[tuple[str, str, str]] = [
    ("Dr. Muhammad Khurram Ehsan", "HOD CS / Sr. Associate Professor",
     "Digital Twin (Wireless/RF); AI-Enabled Next-Gen Networks; SDN; Signal Processing"),
    ("Dr. Muhammad Ramzan", "Sr. Professor",
     "Machine Learning; Medical Imaging; Data Science"),
    ("Dr. Faisal Bashir", "Sr. Professor / Dean & Principal",
     "Computer Vision; Pattern Recognition; Artificial Intelligence"),
    ("Dr. Arif ur Rahman", "Professor / Director Research",
     "Digital Preservation; Data Science; Software Engineering"),
    ("Dr. Samabia Tehseen", "Professor",
     "Computer Vision; Deep Learning; Image Processing"),
    ("Mrs. Saima Jawad", "Sr. Associate Professor",
     "Software Engineering; Human-Computer Interaction"),
    ("Dr. Jafar Hasnain", "Sr. Associate Professor",
     "Wireless Networks; Internet of Things"),
    ("Dr. Asad Ullah", "Sr. Associate Professor",
     "Network Security; Cryptography"),
    ("Dr. Asfand Yar", "Associate Professor",
     "Artificial Intelligence; Data Science"),
    ("Dr. Sabina Akhtar", "Sr. Asst. Professor",
     "Distributed Systems; Formal Methods"),
    ("Dr. Moazam Ali", "Sr. Asst. Professor",
     "Internet of Things; Wireless Communications"),
    ("Dr. Muhammad Usman Hashmi", "Associate Professor",
     "Signal Processing; Machine Learning"),
    ("Dr. Hafiz Ashfaq Ahmad", "Sr. Asst. Professor",
     "Cybersecurity; Computer Networks"),
    ("Dr. Saba Mahmood", "Sr. Asst. Professor",
     "Data Science; Information Security"),
    ("Dr. Asim Ali", "Sr. Asst. Professor",
     "Machine Learning; Cryptography"),
    ("Dr. Muhammad Asif", "Sr. Asst. Professor",
     "Natural Language Processing; Machine Learning"),
    ("Dr. Muhammad Hasan Islam", "Sr. Asst. Professor",
     "Network Security; Cloud Computing"),
    ("Dr. Fatima Khalique", "Asst. Professor",
     "Bioinformatics; Data Science"),
    ("Dr. Naila Shaheen", "Sr. Asst. Professor",
     "Machine Learning; Big Data Analytics"),
    ("Dr. Soahil Akhtar", "Asst. Professor", ""),
    ("Dr. Kabeer Ahmed Bhatti", "Asst. Professor", ""),
    ("Dr. Faryal Nosheen", "Asst. Professor", ""),
    ("Dr. Faisal Imran", "Asst. Professor", ""),
    ("Dr. Farman Ali", "Asst. Professor", ""),
    ("Dr. Arshad Farhad", "Asst. Professor",
     "Internet of Things; Wireless Networks"),
    ("Dr. Erum Ashraf", "Asst. Professor", ""),
    ("Dr. Saneeha Amir", "Asst. Professor", ""),
    ("Dr. Adil Khan", "Asst. Professor",
     "Deep Learning; Computer Vision"),
    ("Dr. Hina Gul", "Asst. Professor", ""),
    ("Dr. Muhammad Umer Mushtaq", "Asst. Professor", ""),
    ("Mrs. Ambrina Kanwal", "Sr. Asst. Professor",
     "Natural Language Processing; Sentiment Analysis"),
    ("Ms. Aliya Amir", "Asst. Professor", ""),
    ("Ms. Mehwish Pervaiz", "Asst. Professor", ""),
    ("Ms. Fouzia Touqeer", "Asst. Professor", ""),
    ("Mr. Ali Irfan Bhatti", "Asst. Professor", ""),
    ("Ms. Mona Leeza", "Asst. Professor", ""),
    ("Mr. Umar Khatak", "Sr. Lecturer", ""),
    ("Mr. Usman Shafique", "Sr. Lecturer", ""),
    ("Ms. Iqra Javed", "Sr. Lecturer", ""),
    ("Ms. Sabira Feroz", "Sr. Lecturer", ""),
    ("Ms. Maryam Bibi", "Sr. Lecturer", ""),
    ("Mr. Qazi Haseeb Yousaf", "Sr. Lecturer", ""),
    ("Ms. Mehroz Sadiq", "Sr. Lecturer", ""),
    ("Ms. Huma Shabbir", "Sr. Lecturer", ""),
    ("Mr. Raja M Shamayel Ullah", "Sr. Lecturer", ""),
    ("Mr. Syed Junaid Hussain", "Sr. Lecturer", ""),
    ("Mr. Saeed Ur Rahman", "Sr. Lecturer", ""),
    ("Ms. Sadia Nazim", "Sr. Lecturer", ""),
    ("Mr. Muhammad Siddique", "Sr. Lecturer", ""),
    ("Mr. Abdul Salam", "Sr. Lecturer", ""),
    ("Mr. Jawwad Ijaz", "Sr. Lecturer", ""),
    ("Ms. Raheela Ansar", "Sr. Lecturer", ""),
    ("Ms. Farwa Kazmi", "Lecturer", ""),
    ("Ms. Nabia Khalid", "Lecturer", ""),
    ("Mr. Abdul Rahman", "Lecturer", ""),
    ("Mr. Qazi Mohsin Ijaz", "Lecturer", ""),
    ("Ms. Nadia Kalsoom", "Lecturer", ""),
    ("Ms. Afrah", "Lecturer", ""),
    ("Ms. Ameena Saeed", "Lecturer", ""),
    ("Mr. M Ahtesham Noor", "Lecturer", ""),
    ("Ms. Asma Basit", "Lecturer", ""),
    ("Mr. Adnan Jelani", "Lecturer", ""),
    ("Mr. Ubaid ur Rahman", "Lecturer", ""),
    ("Mr. Abdul Raheem Aleem", "Lecturer", ""),
    ("Ms. Samia Kiran", "Lecturer", ""),
    ("Ms. Saira Hameed", "Lecturer", ""),
    ("Ms. Aima Zahoor", "Lecturer", ""),
    ("Ms. Bibi Amna", "Lecturer", ""),
]

DEPARTMENT = "Computer Science"
CAMPUS = "Bahria University, Islamabad (E-8)"
